from p4utils.utils.topology import Topology
from p4utils.utils.sswitch_API import *
from crc import Crc
import socket, struct, pickle, os
crc32_polinomials = [0x04C11DB7, 0xEDB88320, 0xDB710641, 0x82608EDB, 0x741B8CD7, 0xEB31D82E,
                     0xD663B05, 0xBA0DC66B, 0x32583499, 0x992C1A4C, 0x32583499, 0x992C1A4C]


class O3Controller(object):

    def __init__(self, sw_name, set_hash):

        self.topo = Topology(db="topology.db")
        self.sw_name = sw_name
        self.set_hash = set_hash
        self.thrift_port = self.topo.get_thrift_port(sw_name)
        self.controller = SimpleSwitchAPI(self.thrift_port)

        self.custom_calcs = self.controller.get_custom_crc_calcs()
        self.register_num = 4 #len(self.custom_calcs)
        print "register_num is {}.".format(self.register_num)

        self.init()
        self.ID_registers = []
        self.Cnt_registers = []
        self.Seq_registers = []

    def init(self):
        if self.set_hash:
            self.set_crc_custom_hashes()
        self.create_hashes()

    def set_forwarding(self):
        self.controller.table_add("forwarding", "set_egress_port", ['1'], ['2'])
        self.controller.table_add("forwarding", "set_egress_port", ['2'], ['1'])

    def reset_registers(self):
        len_ = len(self.controller.register_read("ID1"))
        for j in range(1, self.register_num + 1):
            for i in range(len_):
                self.controller.register_write("ID{}".format(j), i, 0)
                self.controller.register_write("Seq{}".format(j), i, 0)
                self.controller.register_write("Cnt{}".format(j), i, 0)

    def set_crc_custom_hashes(self):
        i = 0
        for custom_crc32, width in sorted(self.custom_calcs.items()):
            self.controller.set_crc32_parameters(custom_crc32, crc32_polinomials[i], 0xffffffff, 0xffffffff, True, True)
            i+=1

    def create_hashes(self):
        self.hashes = []
        for i in range(self.register_num):
            self.hashes.append(Crc(32, crc32_polinomials[i], True, 0xffffffff, True, 0xffffffff))

    def read_registers(self):
        self.ID_registers = []
        self.Cnt_registers = []
        self.Seq_registers = []
        for i in range(1, self.register_num + 1):
            self.ID_registers.append(self.controller.register_read("ID{}".format(i)))
            self.Seq_registers.append(self.controller.register_read("Seq{}".format(i)))
            self.Cnt_registers.append(self.controller.register_read("Cnt{}".format(i)))

    def get_out_of_order_count(self):
        est_flow_o3_dict = {}
        _len = len(self.ID_registers[0])
        print _len
        for i in range(self.register_num):
            for j in range(_len):
                est_flow_o3_dict[self.ID_registers[i][j]] = self.Cnt_registers[i][j]
        return est_flow_o3_dict

    def show(self, ground_truth_file="o3_real.pickle"):

        """In the decoding function you were free to compute whatever you wanted.
           This solution includes a very basic statistic, with the number of flows inside the confidence bound.
        """
        self.read_registers()
        est_flow_o3_dict = self.get_out_of_order_count()
        for flow in est_flow_o3_dict:
            print "The count of {} is {}.".format(flow, est_flow_o3_dict[flow])
        real_flow_o3 = pickle.load(open(ground_truth_file, 'r'))
        sum_are = 0.0
        for flow in real_flow_o3:
            if flow in est_flow_o3_dict:
                _est = est_flow_o3_dict[flow]
            else:
                _est = 0
            sum_are += abs(real_flow_o3[flow] - _est)
        print "The average absolute error is {}.".format(sum_are / len(real_flow_o3))
        '''
        flows = pickle.load(open(ground_truth_file, "r"))
        max_seq_dict = {}
        real_flow_o3_dict = {}
        for flow, n_packets in flows.items():
            if n_packets != 0:
                real_diff_flows.add(flow[0])
        '''

if __name__ == "__main__":

    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument('--sw', help="switch name to configure" , type=str, required=False, default="s1")
    parser.add_argument('--flow-file', help="name of the file generated by send.py", type=str, required=False, default="sent_flows.pickle")
    parser.add_argument('--option', help="controller option can be either set_hashes, decode or reset registers", type=str, required=False, default="set_hashes")
    args = parser.parse_args()

    set_hashes = args.option == "set_hashes"
    controller = O3Controller(args.sw, set_hashes)

    if args.option == "show":
        controller.show()
        #controller.show_sketch()

    elif args.option == "reset":
        controller.reset_registers()
